POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
  "title": "Some Title",
  "author": "Random Guy"
}
###

PUT http://localhost:3003/api/blogs/659afc6a253b082272b4e7fb
Content-Type: application/json

{
"url": "http://bbcita.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
"likes": 533
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{ 
  "username": "elonspice",
  "name": "Elon Spice",
  "password": "spacex"
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
  "title": "The Infinity of Human Imagination",
  "author": "Charlos Cacas",
  "url":  "https://someweb.com/somearticles.html",
  "userId": "65a048f0bafd4a608aa396df"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
  "title": "The Deepest Oceans",
  "author": "Jack DiCaprio",
  "url":  "https://nicepage.com/shitugottaread.html",
  "userId": "65a048f0bafd4a608aa396df"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{ 
  "username": "elonspice",
  "password": "spacex"
}

###

POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsb24gU3BpY2UiLCJpZCI6IjY1YTIwZmJiNGE2MzUzN2MxOTQ1ZTgxYiIsImlhdCI6MTcwNTE3NTc2NywiZXhwIjoxNzA1MTc5MzY3fQ.rcVjvwY6NOXgK0UARNc5v37KXZhIISabUcPAXUlli5U
Content-Type: application/json

{
  "title": "Wonders of Nature",
  "author": "J.P Leon",
  "url":  "https://kkakaka.com/mars.html"
}


###

DELETE http://localhost:3003/api/blogs/65a1fd0e3f0ea1b34c17e805
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2sgS2FrYSIsImlkIjoiNjVhMWZjZjAzZjBlYTFiMzRjMTdlN2ZmIiwiaWF0IjoxNzA1MTE0ODc4LCJleHAiOjE3MDUxMTg0Nzh9.F5pOU8m_wsZTl28DTFcbeymzHGsNSI5xpfJhQYkI8Fs
Content-Type: application/json
